services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: onlinestudy-postgres
    environment:
      POSTGRES_DB: onlinestudy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - onlinestudy-network

  # Redis for job queue
  redis:
    image: redis:7-alpine
    container_name: onlinestudy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - onlinestudy-network

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: onlinestudy-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - onlinestudy-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onlinestudy-backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: onlinestudy
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: onlinestudy-files
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin123
      S3_REGION: us-east-1
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./backend/temp:/app/temp
    networks:
      - onlinestudy-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onlinestudy-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - onlinestudy-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  onlinestudy-network:
    driver: bridge
